// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4lpkijMKM7Q9XAS4BBDHvDdJYcyupcfI',
    appId: '1:288604051311:web:352534b83b578dc565fa9a',
    messagingSenderId: '288604051311',
    projectId: 'todolist-18f8e',
    authDomain: 'todolist-18f8e.firebaseapp.com',
    storageBucket: 'todolist-18f8e.firebasestorage.app',
    measurementId: 'G-44GP5XKQ2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYiWZ_FXPXd8VmgBf5mJCdOibmOF8Aytk',
    appId: '1:288604051311:android:bc5e03a6b4cdc6c565fa9a',
    messagingSenderId: '288604051311',
    projectId: 'todolist-18f8e',
    storageBucket: 'todolist-18f8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw-gWtPISFTugbId3GwCPW1Dq3JIe3SRQ',
    appId: '1:288604051311:ios:6e7b05a6d11b80f965fa9a',
    messagingSenderId: '288604051311',
    projectId: 'todolist-18f8e',
    storageBucket: 'todolist-18f8e.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw-gWtPISFTugbId3GwCPW1Dq3JIe3SRQ',
    appId: '1:288604051311:ios:6e7b05a6d11b80f965fa9a',
    messagingSenderId: '288604051311',
    projectId: 'todolist-18f8e',
    storageBucket: 'todolist-18f8e.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4lpkijMKM7Q9XAS4BBDHvDdJYcyupcfI',
    appId: '1:288604051311:web:53efb6bbe5bfa44165fa9a',
    messagingSenderId: '288604051311',
    projectId: 'todolist-18f8e',
    authDomain: 'todolist-18f8e.firebaseapp.com',
    storageBucket: 'todolist-18f8e.firebasestorage.app',
    measurementId: 'G-WP4MYZKMJ6',
  );
}
